/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daan van Leeuwen (https://sketchfab.com/superwortel)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/satellite-d232fe608c874009bad9613c8093a972
title: Satellite
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Satellite(props) {
  const { nodes, materials } = useGLTF('/satellite.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert1} />
      </group>
    </group>
  )
}

useGLTF.preload('/satellite.gltf')
