/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Oleg Muzyka (https://sketchfab.com/olemuzyka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-5ee15da877a84df3aade63344d9fc1a4
title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/laptop/scene.gltf')
  return (
    <group {...props} dispose={null} castShadow>
      <group rotation={[-Math.PI / 2, 0, 0]} castShadow>
        <mesh geometry={nodes.Object_2.geometry} material={materials.aiStandardSurface5SG} castShadow/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.aiStandardSurface7SG} castShadow/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.aiStandardSurface1SG} castShadow/>
        <mesh geometry={nodes.Object_5.geometry} material={materials.aiStandardSurface3SG} castShadow/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.aiStandardSurface4SG} castShadow/>
        <mesh geometry={nodes.Object_7.geometry} material={materials.aiStandardSurface4SG} castShadow/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.aiStandardSurface4SG} castShadow/>
        <mesh geometry={nodes.Object_9.geometry} material={materials.aiStandardSurface6SG} castShadow/>
        <mesh geometry={nodes.Object_10.geometry} material={materials.initialShadingGroup} castShadow/>
        <mesh geometry={nodes.Object_11.geometry} material={materials.initialShadingGroup} castShadow/>
        <mesh geometry={nodes.Object_12.geometry} material={materials.initialShadingGroup} castShadow/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptop/scene.gltf')
